In [4]:
import pandas as pd, numpy as np
import random,requests
from bs4 import BeautifulSoup
from faker import Faker

import vaex

import numpy as np
import pylab as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

#initialize Faker
fake=Faker()
Faker.seed(4321)


In [5]:
names=[]
address=[]
company=[]

n_names=200
for n in range(n_names):
    names.append(fake.name())
    address.append(fake.address())
    company.append(fake.company())
    

     
        

In [36]:
from numpy.random import randint
from numpy.random import rand


In [ ]:
column_names = []


In [74]:
df = pd.DataFrame() 



In [75]:
df.columns

Index([], dtype='object')

In [76]:
NumColumns = 100
temp3 = rand(NumColumns, 1)
temp = [fake.name()] + [fake.address()] + [fake.company()] + list(randint(100, size=NumColumns)) +  temp3.flatten().tolist()

In [77]:
print(temp)

['James Curry', 'PSC 9053, Box 2401\nAPO AE 42402', 'Carson PLC', 14, 47, 55, 64, 13, 78, 8, 54, 72, 5, 20, 6, 53, 64, 94, 55, 24, 23, 5, 2, 86, 30, 97, 52, 36, 47, 95, 18, 45, 73, 64, 69, 19, 38, 98, 95, 7, 35, 84, 1, 3, 41, 73, 20, 50, 92, 69, 11, 68, 13, 90, 56, 69, 7, 23, 1, 74, 68, 50, 8, 21, 86, 54, 99, 16, 81, 67, 25, 74, 89, 57, 41, 70, 32, 78, 80, 35, 70, 40, 89, 77, 34, 29, 8, 65, 75, 87, 1, 71, 19, 35, 8, 57, 53, 34, 98, 80, 95, 62, 16, 0.6685608349122469, 0.9523571074413099, 0.3137407974686376, 0.7986324778817822, 0.6588053835862325, 0.17512930753395928, 0.876840662526897, 0.8172954021265441, 0.6389106255648537, 0.8707129573000448, 0.14189606121859621, 0.7351437407441932, 0.9884367861914152, 0.012473292958665727, 0.07218290320279652, 0.8561739474312611, 0.6428667778645148, 0.530967415222477, 0.5082824224393835, 0.875151575608086, 0.7440316305270782, 0.8571521898675306, 0.6686281959458988, 0.5643585939807471, 0.6588394017442232, 0.08593955124106412, 0.4981405452759299, 0.054

In [78]:
for i in range(200):
    temp3 = rand(NumColumns, 1)
    temp = [fake.name()] + [fake.address()] + [fake.company()] + list(randint(100, size=NumColumns)) +  temp3.flatten().tolist()
    df.loc[i] = temp

ValueError: cannot set a frame with no defined columns

In [42]:
df.head(5)

name                                            address  \
0   Earl Anderson  7887 Rebecca Plaza Suite 743\nSouth Ronnie, GA...   
1  Kathleen Owens          53156 Samuel Falls\nCurtisshire, AZ 97255   
2    James Butler            68437 Bailey Bypass\nNew Lisa, CT 29825   
3  Kimberly Payne  87461 Mark Corners Suite 737\nRichardville, ID...   
4     Eric Levine      14990 Mark Parkway\nChristopherview, NH 04927   

                         company qty1 qty2 qty3 qty4 qty5 qty6 qty7 qty8 qty9  \
0  Copeland, Mendoza and Rodgers    2    5    2    7    2    3    0    2    6   
1                  Carey-Spencer    6    6    3    6    7    9    8    6    3   
2    Burnett, Olson and Campbell    3    3    3    7    4    8    9    8    6   
3                Williams-Wilson    0    6    9    9    4    5    4    0    7   
4       Skinner, Velez and Ortiz    6    1    8    0    2    5    3    2    6   

  qty10  
0     4  
1     3  
2     1  
3     9  
4     8

In [43]:
df.to_csv("E:/Data/pinnacle/SampleData.csv", index=False)

In [50]:
a = rand(1,10)

In [51]:
print(a)

[[0.98177571 0.2628173  0.73595381 ... 0.83433168 0.21723099 0.00954474]
 [0.00863157 0.53299775 0.81275385 ... 0.74624824 0.02530089 0.00148643]
 [0.87303584 0.84879709 0.81859102 ... 0.15125095 0.03192485 0.73191348]
 ...
 [0.09668523 0.95460982 0.11969158 ... 0.69404639 0.73791433 0.98964189]
 [0.08109133 0.35064614 0.15127997 ... 0.46308193 0.38225701 0.4091412 ]
 [0.61083015 0.03700089 0.94405771 ... 0.28000244 0.08647376 0.52938894]]
